[server]
headless = true
fileWatcherType = "none"
maxUploadSize = 50

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showErrorDetails = false

[theme]
base = "light"
primaryColor = "#1B873F"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F3F6F4"
textColor = "#10241A"
